---   
    - name: Install nodejs
      apt: name=nodejs state=present

    - name: install node-legacy
      apt: name=nodejs-legacy state=present

    - name: install npm
      apt: name=npm state=present

